".antigen/antigen.zsh":
  type: file
  url: https://raw.githubusercontent.com/zsh-users/antigen/HEAD/bin/antigen.zsh
{{  if not .is_devcontainer | and .is_gnome -}}
".local/bin/gnome-shell-extension-installer":
  type: file
  url: https://raw.githubusercontent.com/brunelli/gnome-shell-extension-installer/HEAD/gnome-shell-extension-installer
  executable: true
# Downloads all the variants of Fira Code Nerd Font
{{-   range $_, $face := list "Regular" "Light" "Medium" "Bold" "Retina" "SemiBold" -}}
{{-     range $_, $variant := list "" " Mono" }}
".local/share/fonts/Fira Code {{ $face }} Nerd Font Complete{{ $variant }}.ttf":
  type: file
  url: https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/FiraCode/{{ $face }}/complete/Fira%20Code%20{{ $face }}%20Nerd%20Font%20Complete{{ $variant | replace " " "%20" }}.ttf
{{      end -}}
{{-   end -}}
{{- end -}}
